# -*- coding: utf-8 -*-
"""[Ver6][MFCC][LightCNN] ConvertToTFLite

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dgWP799XWJZayS4vQOvMiBDap97NlQB-
"""

from google.colab import drive
drive.mount('/content/drive')

import sys
from pathlib import Path
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
import h5py
import pandas as pd
import torch.nn as nn
# Define the project path
PROJECT_PATH = Path('/content/drive/MyDrive/AutomaticHeartSoundClassification-main')
sys.path.append(str(PROJECT_PATH))

DATASET_PATH = Path('/content/drive/MyDrive/AutomaticHeartSoundClassification-main/data')
sys.path.append(str(DATASET_PATH))

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

DATARAW_PATH = Path('/content/drive/MyDrive/physionet2016')
sys.path.append(str(DATASET_PATH))

MODEL_NAME = "Light_CNN"      # hoặc "CNN"
TIMESTAMP = "0228_045450"

"""# Dowload Package"""

import importlib
import subprocess
import sys

def check_or_install(pkg_name, import_name=None, version=None):
    """
    Check whether a Python package is already installed.
    If the package exists, print its current version.
    If the package does not exist, install the specified version.

    Parameters
    ----------
    pkg_name : str
        Package name as registered on PyPI.
    import_name : str, optional
        Module name used for import (if different from pkg_name).
    version : str, optional
        Required version. If None, any installed version is accepted.
    """
    name = import_name if import_name else pkg_name

    try:
        # Try to import the package
        module = importlib.import_module(name)

        # Retrieve the package version if available
        ver = getattr(module, "__version__", "unknown")

        print(f"[OK] {pkg_name} is already installed (version: {ver})")

    except ImportError:
        # Construct the pip install command
        install_target = pkg_name if version is None else f"{pkg_name}=={version}"

        print(f"[INSTALL] {pkg_name} not found. Installing {install_target} ...")

        # Install the package using pip
        subprocess.check_call([
            sys.executable,
            "-m",
            "pip",
            "install",
            install_target
        ])

#pip uninstall numpy==2.0.2

"""Sau khi tải xong onxx bên dưới thì uncomment uninstall 2.0.2 và 1.26.4 để tải 1.26.4"""

#pip install numpy==1.26.4

check_or_install("numpy", version="1.26.4")

#pip uninstall -y onnx onnxsim onnxruntime onnxscript onnx2tf onnx-graphsurgeon

check_or_install("onnx", version="1.17.0")

# Core ONNX ecosystem (recommended stable versions)
check_or_install("onnx", version="1.17.0")
#check_or_install("onnxsim", import_name="onnxsim", version="0.4.36")
check_or_install("onnxsim", import_name="onnxsim")
check_or_install("onnx-graphsurgeon", import_name="onnx_graphsurgeon")

# Runtime and model conversion tools
check_or_install("onnxruntime", import_name="onnxruntime", version="1.18.1")
check_or_install("onnx2tf", import_name="onnx2tf")
check_or_install("onnxscript", import_name="onnxscript")

# TensorFlow and Keras (stable and compatible versions)
check_or_install("tensorflow", import_name="tensorflow", version="2.19.0")
check_or_install("tf-keras", import_name="tf_keras", version="2.19.0")

# Auxiliary packages for signal processing and edge deployment
check_or_install("h5py")
check_or_install("librosa")
check_or_install("ai_edge_litert", version="1.2.0")
check_or_install("sng4onnx")

"""# Loss and Metrics"""

import torch.nn.functional as F


def nll_loss(output, target):
    return F.nll_loss(output, target)

def ce_loss(output, target):
    return F.cross_entropy(output, target)

import torch


def accuracy(output, target):
    with torch.no_grad():
        pred = torch.argmax(output, dim=1)
        assert pred.shape[0] == len(target)
        correct = 0
        correct += torch.sum(pred == target).item()
    return correct / len(target)


def top_k_acc(output, target, k=3):
    with torch.no_grad():
        pred = torch.topk(output, k, dim=1)[1]
        assert pred.shape[0] == len(target)
        correct = 0
        for i in range(k):
            correct += torch.sum(pred[:, i] == target).item()
    return correct / len(target)

class FocalLoss(nn.Module):
    def __init__(self, alpha=0.25, gamma=1.5):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, inputs, targets):
        weight = torch.tensor(
            [1 - self.alpha, self.alpha], device=inputs.device
        ).float()   # [w_normal, w_abnormal]
        ce_loss = F.cross_entropy(inputs, targets, weight=weight, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = (1 - pt) ** self.gamma * ce_loss
        return focal_loss.mean()

MODEL_DIR_MAP = {
    "VGG11": "VGG11",
    "CNN": "simple_cnn",
    "CRNN": "CRNN",
    "LSTM": "LSTM",
    "Light_CNN": "lightweight_cnn",
}

def standard_normal_variate(data):
    mean = np.mean(data)
    std = np.std(data) + EPS
    return (data - mean) / std

class MFCCDataset(Dataset):
    def __init__(
        self,
        features_h5_path,
        label_csv_path,
        keys=None,
        norm=True,
        duration=5,
        hop_length=15,
        training=False
    ):
        self.features_h5 = h5py.File(features_h5_path, 'r')
        self.labels_df = pd.read_csv(label_csv_path)

        self.keys = list(self.features_h5.keys()) if keys is None else keys
        self.key_to_label = dict(
            zip(
                self.labels_df.iloc[:, 0].astype(str),
                self.labels_df.iloc[:, 1]
            )
        )

        self.norm = norm
        self.training = training
        self.fixed_length = int(duration * 1000 / hop_length)  # 333

    def __len__(self):
        return len(self.keys)

    def __getitem__(self, idx):
        key = self.keys[idx]

        # MFCC gốc: (13, T)
        mfcc = self.features_h5[key][()].astype(np.float32)

        if self.norm:
            mfcc = standard_normal_variate(mfcc)

        n_mfcc, T = mfcc.shape

        # crop / pad time axis
        if T >= self.fixed_length:
            start = (T - self.fixed_length) // 2
            mfcc = mfcc[:, start:start + self.fixed_length]
        else:
            pad = self.fixed_length - T
            mfcc = np.pad(mfcc, ((0, 0), (0, pad)), mode="constant")

        # FINAL SHAPE: (13, 333)
        feature_tensor = torch.from_numpy(mfcc)
        label = torch.tensor(self.key_to_label.get(key, 0), dtype=torch.long)

        return feature_tensor, label

    def close(self):
        self.features_h5.close()

"""# Config Parse"""

import os
import logging
from pathlib import Path
from datetime import datetime
import argparse
import collections
import importlib.util

class ConfigParser:
    def __init__(self, config_dict, resume=None, modification=None, run_id=None):
        self._config = config_dict
        self.resume = resume

        # Apply CLI modifications
        if modification:
            for key_path, value in modification.items():
                keys = key_path.split(';')
                d = self._config
                for k in keys[:-1]:
                    d = d[k]
                d[keys[-1]] = value

        # Setup save and log directories
        save_dir = Path(self.config['trainer']['save_dir'])
        exper_name = self.config['name']
        if run_id is None:
            run_id = datetime.now().strftime(r'%m%d_%H%M%S')
        self._save_dir = save_dir / 'models' / exper_name / run_id
        self._log_dir = save_dir / 'log' / exper_name / run_id

        self.save_dir.mkdir(parents=True, exist_ok=True)
        self.log_dir.mkdir(parents=True, exist_ok=True)

        # Optional: setup logging
        # setup_logging(self.log_dir)

    @classmethod
    def from_args(cls, parser, options=None):
        """
        parser: argparse.ArgumentParser đã được add_argument xong
        options: list các CustomArgs để override
        """
        if options is None:
            options = []

        # Parse arguments (an toàn cho cả terminal và notebook)
        args = parser.parse_args()

        # Xử lý device
        if args.device is not None:
            os.environ["CUDA_VISIBLE_DEVICES"] = args.device

        # Xử lý resume
        if args.resume is not None:
            resume = Path(args.resume)
            cfg_fname = resume.parent / 'config.py'  # hoặc .json nếu bạn dùng cả 2
        else:
            resume = None
            assert args.config is not None, "Phải chỉ định -c config.py"
            cfg_fname = Path(args.config)

        # Đọc config từ file .py
        if not cfg_fname.exists():
            raise FileNotFoundError(f"Không tìm thấy config file: {cfg_fname}")

        if cfg_fname.suffix == '.py':
            spec = importlib.util.spec_from_file_location("config_module", cfg_fname)
            config_module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(config_module)
            if not hasattr(config_module, 'config'):
                raise ValueError(f"File {cfg_fname} phải định nghĩa biến 'config'")
            config_dict = config_module.config
        else:
            raise ValueError("Chỉ hỗ trợ file config .py")

        # Parse custom CLI overrides
        CustomArgs = collections.namedtuple('CustomArgs', 'flags type target')
        modification = {}
        for opt in options:
            for flag in opt.flags:
                arg_name = flag.lstrip('-').replace('-', '_')
                if hasattr(args, arg_name) and getattr(args, arg_name) is not None:
                    modification[opt.target] = opt.type(getattr(args, arg_name))

        return cls(config_dict, resume, modification)

    def init_obj(self, name, module, *args, **kwargs):
        module_name = self[name]['type']
        module_args = dict(self[name]['args'])
        module_args.update(kwargs)
        if isinstance(module, dict):
            obj_class = module[module_name]
        else:
            obj_class = getattr(module, module_name)

        return obj_class(*args, **module_args)

    def init_ftn(self, name, module, *args, **kwargs):
        from functools import partial
        module_name = self[name]['type']
        module_args = dict(self[name]['args'])
        module_args.update(kwargs)
        if isinstance(module, dict):
            obj_class = module[module_name]
        else:
            obj_class = getattr(module, module_name)

        return obj_class(*args, **module_args)

    def __getitem__(self, name):
        return self.config[name]

    def get_logger(self, name, verbosity=2):
        logger = logging.getLogger(name)
        logger.setLevel({0: logging.WARNING, 1: logging.INFO, 2: logging.DEBUG}[verbosity])
        return logger

    @property
    def config(self):
        return self._config

    @property
    def save_dir(self):
        return self._save_dir

    @property
    def log_dir(self):
        return self._log_dir

"""# Model"""

import torch.nn as nn
import numpy as np
from abc import abstractmethod


class BaseModel(nn.Module):
    """
    Base class for all models
    """
    def __init__(self):
        super().__init__()

    @abstractmethod
    def forward(self, *inputs):
        """
        Forward pass logic

        :return: Model output
        """
        raise NotImplementedError

    def __str__(self):
        """
        Model prints with number of trainable parameters
        """
        model_parameters = filter(lambda p: p.requires_grad, self.parameters())
        params = sum([np.prod(p.size()) for p in model_parameters])
        return super().__str__() + '\nTrainable parameters: {}'.format(params)

import torch
import torch.nn as nn
import torch.nn.functional as F


# functions of initializing layers
def init_layer(layer):
    """Initialize a Linear or Convolutional layer."""
    nn.init.xavier_uniform_(layer.weight)

    if hasattr(layer, 'bias'):
        if layer.bias is not None:
            layer.bias.data.fill_(0.)

def init_bn(bn):
    """Initialize a Batchnorm layer."""
    bn.bias.data.fill_(0.)
    bn.weight.data.fill_(1.)

def init_rnn(rnn):
    """init_rnn
    Initialized RNN weights, independent of type GRU/LSTM/RNN
    :param rnn: the rnn model
    """
    for name, param in rnn.named_parameters():
        if 'bias' in name:
            nn.init.constant_(param, 0.0)
        elif 'weight' in name:
            nn.init.xavier_uniform_(param)

def reset_parameters(model):
    for module in model.modules():
        if isinstance(module, nn.Conv2d):
            init_layer(module)
        elif isinstance(module, nn.Linear):
            init_layer(module)
        elif isinstance(module, nn.BatchNorm2d):
            init_bn(module)
        elif isinstance(module, nn.LSTM):
            init_rnn(module)

"""## CNN

## Lightweight CNN Architecture
"""

class SEBlock(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()  # Fix: thiếu dòng này trong code gốc
        self.squeeze = nn.AdaptiveAvgPool2d(1)
        self.excitation = nn.Sequential(
            nn.Linear(channels, channels // reduction),   # 128→8: 1024 params
            nn.ReLU(),
            nn.Linear(channels // reduction, channels),   # 8→128: 1024 params
            nn.Sigmoid()
        )

    def forward(self, x):  # Fix: thiếu forward() trong code gốc
        B, C, _, _ = x.shape
        s = self.squeeze(x).view(B, C)        # (B, C)
        e = self.excitation(s).view(B, C, 1, 1)  # (B, C, 1, 1)
        return x * e                           # channel-wise scaling


class DepthwiseSeparableConv(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1):
        super().__init__()
        self.depthwise = nn.Conv2d(in_channels, in_channels, kernel_size,
                                   stride, padding, groups=in_channels, bias=False)
        self.pointwise = nn.Conv2d(in_channels, out_channels, 1, bias=False)
        self.bn = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU6(inplace=True)

    def forward(self, x):
        x = self.depthwise(x)
        x = self.pointwise(x)
        x = self.bn(x)
        return self.relu(x)

# === THÊM MỚI (chèn sau dòng 1101) ===

class GhostModule(nn.Module):
    """
    Tạo 2*out//2 = out feature maps: nửa từ conv thật, nửa từ depthwise rẻ tiền.
    Tiết kiệm ~50% tham số so với Conv2d thông thường.
    """
    def __init__(self, in_channels, out_channels, stride=1):
        super().__init__()
        init_channels = out_channels // 2          # nửa từ conv thật
        ghost_channels = out_channels - init_channels  # nửa còn lại

        # Conv chính: tạo feature maps "thật"
        self.primary = nn.Sequential(
            nn.Conv2d(in_channels, init_channels, kernel_size=1, stride=stride, bias=False),
            nn.BatchNorm2d(init_channels),
            nn.ReLU6(inplace=True)
        )
        # Depthwise: tạo feature maps "ghost" từ primary output
        self.ghost = nn.Sequential(
            nn.Conv2d(init_channels, ghost_channels, kernel_size=3,
                      stride=1, padding=1, groups=init_channels, bias=False),
            nn.BatchNorm2d(ghost_channels),
            nn.ReLU6(inplace=True)
        )

    def forward(self, x):
        p = self.primary(x)         # (B, out//2, H, W)
        g = self.ghost(p)           # (B, out//2, H, W)
        return torch.cat([p, g], dim=1)  # (B, out, H, W)


class ShuffleBlock(nn.Module):
    """
    ShuffleNet V2-style block: split → branch → concat → shuffle.
    Không tốn thêm tham số cho việc trao đổi thông tin giữa các nhóm.
    """
    def __init__(self, in_channels, out_channels, stride=1):
        super().__init__()
        self.stride = stride
        branch_channels = out_channels // 2

        if stride == 1:
            # Branch phải: xử lý nửa channels
            self.branch_right = nn.Sequential(
                nn.Conv2d(in_channels // 2, branch_channels, 1, bias=False),
                nn.BatchNorm2d(branch_channels),
                nn.ReLU6(inplace=True),
                nn.Conv2d(branch_channels, branch_channels, 3, stride=1,
                          padding=1, groups=branch_channels, bias=False),
                nn.BatchNorm2d(branch_channels),
                nn.Conv2d(branch_channels, branch_channels, 1, bias=False),
                nn.BatchNorm2d(branch_channels),
                nn.ReLU6(inplace=True)
            )
            # Branch trái: identity (không có tham số)
        else:
            # stride=2: cả 2 branch đều có conv để downsample
            self.branch_left = nn.Sequential(
                nn.Conv2d(in_channels, in_channels, 3, stride=stride,
                          padding=1, groups=in_channels, bias=False),
                nn.BatchNorm2d(in_channels),
                nn.Conv2d(in_channels, branch_channels, 1, bias=False),
                nn.BatchNorm2d(branch_channels),
                nn.ReLU6(inplace=True)
            )
            self.branch_right = nn.Sequential(
                nn.Conv2d(in_channels, branch_channels, 1, bias=False),
                nn.BatchNorm2d(branch_channels),
                nn.ReLU6(inplace=True),
                nn.Conv2d(branch_channels, branch_channels, 3, stride=stride,
                          padding=1, groups=branch_channels, bias=False),
                nn.BatchNorm2d(branch_channels),
                nn.Conv2d(branch_channels, branch_channels, 1, bias=False),
                nn.BatchNorm2d(branch_channels),
                nn.ReLU6(inplace=True)
            )

    @staticmethod
    def channel_shuffle(x, groups=2):
        """Shuffle channels giữa các group — không tốn tham số."""
        B, C, H, W = x.shape
        x = x.view(B, groups, C // groups, H, W)
        x = x.transpose(1, 2).contiguous()
        return x.view(B, C, H, W)

    def forward(self, x):
        if self.stride == 1:
            # Split: nửa trái identity, nửa phải qua branch
            left, right = x.chunk(2, dim=1)
            out = torch.cat([left, self.branch_right(right)], dim=1)
        else:
            out = torch.cat([self.branch_left(x), self.branch_right(x)], dim=1)

        return self.channel_shuffle(out, groups=2)

class LightweightHeartSoundCNN(nn.Module):
    """
    Ghost-SE + ShuffleBlock, channel progression: in → 24 → 48 → 96 → 128
    Target: ~25k–35k params
    """
    def __init__(self, num_classes=2, in_channel=1, dropout=0.2):
        super().__init__()
        self.in_channel = in_channel

        # Stem: in_channel → 24
        self.stem = nn.Sequential(
            nn.Conv2d(in_channel, 24, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(24),
            nn.ReLU6(inplace=True)
        )

        # Stage 1: 24 → 48, stride=2
        self.stage1 = ShuffleBlock(24, 48, stride=2)

        # Stage 2: 48 → 96, stride=2
        self.stage2 = ShuffleBlock(48, 96, stride=2)

        # Stage 3: 96 → 128, stride=2
        self.stage3 = ShuffleBlock(96, 128, stride=2)

        self.drop = nn.Dropout2d(0.1)

        # SE block: reduction=16 để tiết kiệm params
        self.se = SEBlock(channels=128, reduction=16)

        # Spatial attention: Conv 128→1
        self.spatial_attn = nn.Sequential(
            nn.Conv2d(128, 1, kernel_size=1, bias=False),
            nn.Sigmoid()
        )

        # Classifier: GAP → FC nhỏ → output
        self.dropout = nn.Dropout(dropout)
        self.classifier = nn.Sequential(
            nn.Linear(128, 32),
            nn.ReLU6(),
            nn.Dropout(dropout),
            nn.Linear(32, num_classes)
        )

    def forward(self, x):
        B, F, T = x.shape
        #x = x.view(B, self.in_channel, F // self.in_channel, T)
        x = x.unsqueeze(1)

        x = self.stem(x)

        x = self.stage1(x)
        x = self.drop(x)
        x = self.stage2(x)
        x = self.drop(x)
        x = self.stage3(x)

        # Channel attention
        x = self.se(x)

        # Spatial attention
        attn = self.spatial_attn(x)
        x = x * attn

        # GAP → FC
        x = x.mean(dim=[2, 3])     # (B, 128)
        x = self.dropout(x)
        return self.classifier(x)

"""## Deeper CNN model, VGG like structure

## RNN - BiLTSM

## CRNN

# Load Model
"""

from pathlib import Path

def get_model_best_path(project_path, model_name, timestamp):
    """
    Trả về đường dẫn tới model_best.pth theo cấu trúc chuẩn:
    saved/<model_dir>/models/Physionet_<model_dir>/<timestamp>/model_best.pth
    """

    if model_name not in MODEL_DIR_MAP:
        raise ValueError(f"Unsupported model name: {model_name}")

    model_dir = MODEL_DIR_MAP[model_name]

    return (
        project_path
        / "saved"
        / model_dir
        / "models"
        / f"Physionet_{model_dir}"
        / timestamp
        / "model_best.pth"
    )

model_path = get_model_best_path(
    project_path=PROJECT_PATH,
    model_name=MODEL_NAME,
    timestamp=TIMESTAMP
)

print(model_path)

if model_path.exists():
    size_bytes = model_path.stat().st_size

    # Convert to human-readable format
    if size_bytes < 1024:
        size_str = f"{size_bytes} Bytes"
    elif size_bytes < 1024**2:
        size_str = f"{size_bytes / 1024:.2f} KB"
    elif size_bytes < 1024**3:
        size_str = f"{size_bytes / (1024**2):.2f} MB"
    else:
        size_str = f"{size_bytes / (1024**3):.2f} GB"

    print(f"✅ File exists!")
    print(f"   Size: {size_str} ({size_bytes:,} bytes)")
else:
    print("File does NOT exist at the specified path.")
    print("   Possible reasons:")
    print("   - Training did not complete or model_best.pth was not saved")
    print("   - Wrong timestamp (check your actual training time)")
    print("   - Model saved elsewhere (e.g., in TFLITE folder)")
    print()
    print("Searching for all .pth files in the project for suggestions...")

    # Search for any .pth files in the entire project
    pth_files = sorted(PROJECT_PATH.rglob("*.pth"))
    if pth_files:
        print("\nFound .pth files:")
        for p in pth_files[:10]:  # Show max 10 files
            rel_size = p.stat().st_size / (1024**2)
            print(f"   → {p.relative_to(PROJECT_PATH)}  ({rel_size:.2f} MB)")
        if len(pth_files) > 10:
            print(f"   ... and {len(pth_files)-10} more files")
    else:
        print("   No .pth files found in the entire project!")

MODEL_CLASS_MAP = {
    "Light_CNN": {
        "class": LightweightHeartSoundCNN,
        "in_channel": 1,
        "num_classes": 2
    }
}

def build_model_for_convert(model_name: str, cfg: dict):
    ModelClass = cfg["class"]
    model_cfg = cfg["model"]
    input_cfg = cfg["input"]

    # ===== CRNN =====
    if model_name == "CRNN":
        model = ModelClass(
            in_channel=input_cfg["in_channel"],
            hidden_dim=model_cfg["hidden_dim"],
            num_layers=model_cfg["num_layers"],
            dropout=model_cfg["dropout"],
            pooling=model_cfg["pooling"],
            model=model_cfg["rnn_type"],
            BN=model_cfg["BN"],
            num_classes=model_cfg["num_classes"]
        )

    # ===== LSTM =====
    elif model_name == "LSTM":
        model = ModelClass(
            input_dim=input_cfg["mel_bins"],
            hidden_dim=model_cfg["hidden_dim"],
            num_layers=model_cfg["num_layers"],
            dropout=model_cfg["dropout"],
            num_classes=model_cfg["num_classes"]
        )

    # ===== CNN / VGG =====
    else:
        model = ModelClass(
            in_channel=input_cfg["in_channel"],
            num_classes=model_cfg["num_classes"]
        )

    model.eval()
    return model

# =========================
# CHECK MODEL NAME
# =========================
if MODEL_NAME not in MODEL_CLASS_MAP:
    raise ValueError(
        f"Model {MODEL_NAME} không được hỗ trợ. "
        f"Các model hỗ trợ: {list(MODEL_CLASS_MAP.keys())}"
    )

cfg = MODEL_CLASS_MAP[MODEL_NAME]
ModelClass = cfg["class"]

# =========================
# BUILD MODEL (THEO KIẾN TRÚC)
# =========================
if MODEL_NAME == "CRNN":
    model = ModelClass(
        in_channel=cfg["in_channel"],
        num_classes=cfg["num_classes"],
        **cfg.get("extra_kwargs", {})
    )

elif MODEL_NAME == "LSTM":
    # LSTM ở đây là BiLSTM, không dùng in_channel
    model = ModelClass(
        num_classes=cfg["num_classes"],
        **cfg.get("extra_kwargs", {})
    )

elif MODEL_NAME in ["VGG11", "CNN", "Light_CNN"]:
    model = ModelClass(
        in_channel=cfg["in_channel"],
        num_classes=cfg["num_classes"]
    )

else:
    raise ValueError("Cấu hình model không hợp lệ")

model.to(device)
model.eval()

"""# Punning"""

import torch.nn.utils.prune as prune

parameters_to_prune = []
for name, module in model.named_modules():
    if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear)):
        parameters_to_prune.append((module, 'weight'))
        # Optional: prune bias too
        # if module.bias is not None:
        #     parameters_to_prune.append((module, 'bias'))

prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.2,
)

print("✅ Đã apply pruning (với mask)")

features_file = DATASET_PATH / "mfcc_features.h5"
label_file = DATASET_PATH / "label_balanced.csv"

import librosa
import random
import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

EPS = 1e-8

def standard_normal_variate(data):
    """Z-score normalization trên toàn bộ feature"""
    mean = np.mean(data)
    std = np.std(data) + EPS
    return (data - mean) / std

class LogMelDataset(Dataset):
    def __init__(self, features_h5_path, label_csv_path, keys=None,
                 delta=True, norm=True, duration=5, hop_length=15, training=True):
        self.features_h5 = h5py.File(features_h5_path, 'r')
        self.labels_df = pd.read_csv(label_csv_path)

        if keys is None:
            self.keys = list(self.features_h5.keys())
        else:
            self.keys = keys

        # Map key (filename stem) → label
        self.key_to_label = dict(zip(self.labels_df.iloc[:, 0].astype(str), self.labels_df.iloc[:, 1]))

        self.delta = delta
        self.norm = norm
        self.duration = duration
        self.hop_length = hop_length
        self.training = training

        # Độ dài cố định: 5 giây với hop 15ms → 5000 / 15 = 333.333 → lấy 333 frames
        self.fixed_length = int(self.duration * 1000 / self.hop_length)  # 333

    def __len__(self):
        return len(self.keys)

    def __getitem__(self, idx):
        key = self.keys[idx]
        feature = self.features_h5[key][()] # Shape: (C, 13, T) or (13, T)

        # Chuẩn hóa Z-score nếu bật
        if self.norm:
            feature = standard_normal_variate(feature)

        # Đảm bảo luôn là 3D: (C, mel_bins, T)
        if feature.ndim == 2:
            feature = feature[np.newaxis, :, :]  # (1, 128, T)

        channels, mel_bins, num_frames = feature.shape

        # Crop hoặc pad để đạt đúng fixed_length (333 frames)
        if num_frames >= self.fixed_length:
            start = (num_frames - self.fixed_length) // 2
            feature = feature[:, :, start:start + self.fixed_length]
        else:
            pad_width = ((0, 0), (0, 0), (0, self.fixed_length - num_frames))
            feature = np.pad(feature, pad_width, mode='wrap')

        # Bây giờ feature chắc chắn là (channels, 128, 333)
        feature_tensor = torch.from_numpy(feature).float()

        # Quan trọng: reshape để phù hợp với model VGG_11 gốc
        if channels > 1:  # delta=True → ghép 3 channel thành 384 mel bins
            feature_tensor = feature_tensor.view(channels * mel_bins, -1)  # (384, 333)
        else:
            feature_tensor = feature_tensor.squeeze(0)  # (128, 333)

        label = torch.tensor(self.key_to_label.get(key, 0), dtype=torch.long)
        return feature_tensor, label

    def close(self):
        if hasattr(self, 'features_h5'):
            self.features_h5.close()

# ================== CHIA TRAIN/VAL KEYS ==================
# Load toàn bộ keys từ file .h5
with h5py.File(features_file, 'r') as hf:
    all_keys = list(hf.keys())

# Load labels để stratify (giữ tỷ lệ lớp khi chia train/val)
labels_all = pd.read_csv(label_file).iloc[:, 1].values  # cột label (thường là cột thứ 2)

# Chia 80/20, giữ nguyên tỷ lệ nhãn (rất quan trọng cho dataset imbalance như PhysioNet)
train_keys, val_keys = train_test_split(
    all_keys,
    test_size=0.2,
    random_state=42,
    stratify=labels_all
)

print(f"Total samples: {len(all_keys)}")
print(f"Train samples: {len(train_keys)}, Val samples: {len(val_keys)}")

train_dataset = MFCCDataset(
    features_file,
    label_file,
    keys=train_keys,
    #delta=False,
    norm=True,
    duration=5,
    hop_length=15,
    training=True
)

val_dataset = MFCCDataset(
    features_file,
    label_file,
    keys=val_keys,
    #delta=False,
    norm=True,
    duration=5,
    hop_length=15,
    training=False
)

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    num_workers=2,        # giảm xuống 2 để tránh warning
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print(f"Train samples: {len(train_dataset)}, Val samples: {len(val_dataset)}")
print("Mỗi sample có shape cố định → không cần padding trong collate")

model.train()
optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=1e-5)
#criterion = torch.nn.NLLLoss()  # vì model output log_softmax
focal = FocalLoss(alpha=0.6, gamma=2.0)
ce_smooth = nn.CrossEntropyLoss(label_smoothing=0.05)

criterion = lambda pred, target: (
    0.8 * focal(pred, target) +
    0.2 * ce_smooth(pred, target)
)
num_finetune_epochs = 50

for epoch in range(num_finetune_epochs):
    model.train()
    running_loss = 0.0

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    avg_loss = running_loss / len(train_loader)
    print(f"Fine-tune Epoch {epoch+1}/{num_finetune_epochs} - Avg Loss: {avg_loss:.6f}")

    # Đánh giá trên validation (tùy chọn)
    if (epoch + 1) % 5 == 0 or epoch == num_finetune_epochs - 1:
        model.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = model(inputs)
                pred = torch.argmax(outputs, dim=1)
                correct += (pred == labels).sum().item()
                total += labels.size(0)
        acc = correct / total if total > 0 else 0
        print(f"   >>> Val Accuracy sau epoch {epoch+1}: {acc:.4f}")
        model.train()

# Đóng dataset để giải phóng file handle
train_dataset.close()
val_dataset.close()

model.eval()
print("Fine-tune sau pruning hoàn tất")

# ================== LÀM PRUNING PERMANENT ==================
import torch.nn.utils.prune as prune  # nếu chưa import

for module, name in parameters_to_prune:
    prune.remove(module, name)

print("✅ Đã remove pruning mask → pruning permanent")

# ================== LƯU MODEL PRUNED ==================
PRUNED_PATH = PROJECT_PATH / "TFLITE" / f"{MODEL_NAME.lower()}_{TIMESTAMP}_pruned_finetuned.pth"
torch.save(model.state_dict(), PRUNED_PATH)
print(f"✅ Model pruned + finetuned lưu tại: {PRUNED_PATH}")

# Đóng h5 file
train_dataset.close()

"""## Define input shape & Dummy input"""

N_MFCC = 39
T = 333   # hoặc chiều thời gian bạn đang dùng

dummy_input = torch.randn(1, N_MFCC, T).to(device)

device = torch.device("cpu")

model = model.to(device)
dummy_input = dummy_input.to(device)
model.eval()

"""# Chuyển sang ONXX"""

# Export
ONNX_PATH = PROJECT_PATH / "TFLITE" / f"{MODEL_NAME.lower()}_{TIMESTAMP}_final.onnx"
ONNX_PATH.parent.mkdir(parents=True, exist_ok=True)
print(ONNX_PATH)

original_forward = model.forward

def export_forward_simple_cnn(input):
    """
    ONNX-compatible forward for simple_cnn
    Consistent with training architecture
    """
    B, mel_bins, num_frames = input.size()

    # (B, mel, time) → (B, C, mel, time)
    x = input.view(B, model.in_channel, mel_bins, num_frames)

    # -------- Block 1 --------
    x = F.relu(model.bn1(model.conv1(x)))
    x = model.drop1(x)
    x = F.max_pool2d(x, kernel_size=(1, 2))

    # -------- Block 2 --------
    x = F.relu(model.bn2(model.conv2(x)))
    x = model.drop2(x)
    x = F.max_pool2d(x, kernel_size=(1, 2))

    # -------- Block 3 --------
    x = F.relu(model.bn3(model.conv3(x)))
    x = model.drop3(x)

    # -------- Global Average Pooling --------
    x = model.gap(x)          # (B, 64, 1, 1)
    x = x.view(B, -1)         # (B, 64)

    # -------- Classifier --------
    output = model.classifier(x)  # KHÔNG softmax (đúng cho edge / ONNX)

    return output


def export_forward_vgg(input):
    B, mel_bins, num_frames = input.size()
    x = input.view(B, model.in_channel, -1, num_frames)
    x = x.transpose(1, 2)
    x = model.bn0(x)
    x = x.transpose(1, 2)

    x = model.conv1(x, pool_size=(2, 2), pool_type='max')

    x = nn.AdaptiveMaxPool2d((1, 1))(x)
    x = x.view(B, -1)
    output = model.fc_final(x)
    return output

def export_forward_crnn(input):
    """
    ONNX-compatible forward pass
    Uses fixed kernel size for pooling instead of adaptive pooling
    """
    B, mel_bins, num_frames = input.size()

    # Reshape
    x = input.view(B, model.in_channel, mel_bins // model.in_channel, num_frames)

    # CNN encoder - this includes 4 ConvBlocks with pooling
    x = model.cnn(x)

    # Pool frequency dimension using FIXED kernel size
    # This replaces F.adaptive_max_pool2d(x, (1, None))
    x = torch.nn.functional.max_pool2d(
        x,
        kernel_size=(freq_dim_after_cnn, 1)  # Use calculated size
    )
    x = x.squeeze(2)  # Remove frequency dimension

    # BiLSTM
    output = model.bilstm(x)

    return output

original_forward = model.forward

def export_forward_lightcnn(input):
    """
    ONNX-compatible forward for LightweightHeartSoundCNN (Ver 8)
    """
    B, CMel, T = input.size()
    # Chuyển (B, 39, 333) -> (B, 3, 13, 333)
    x = input.view(B, model.in_channel, CMel // model.in_channel, T)

    x = model.stem(x)
    x = model.stage1(x)
    x = model.stage2(x)
    x = model.stage3(x)
    x = model.se(x)
    x = x * model.spatial_attn(x)
    x = x.mean(dim=[2, 3])
    output = model.classifier(x)
    return output

if MODEL_NAME == "CNN":
    model.forward = export_forward_simple_cnn
elif MODEL_NAME == "VGG11":
    model.forward = export_forward_vgg
elif MODEL_NAME == "CRNN":
    model.forward = export_forward_crnn
elif MODEL_NAME == "Light_CNN":
    model.forward = export_forward_lightcnn
else:
    raise ValueError("Unsupported model")

try:
    torch.onnx.export(
        model,
        dummy_input,
        str(ONNX_PATH),
        export_params=True,
        opset_version=17, #18
        do_constant_folding=True,
        input_names=["input"],
        output_names=["output"],
        dynamic_axes={
            "input": {0: "batch_size"},
            "output": {0: "batch_size"}
        },
        dynamo=False
        # verbose=False
    )
    print(f"✅ Export ONNX thành công: {ONNX_PATH}")
except Exception as e:
    print("Lỗi export:", e)
finally:
    model.forward = original_forward
    print("Đã khôi phục forward gốc")

# Kiểm tra file
import os
if os.path.exists(ONNX_PATH):
    print(f"Size: {os.path.getsize(ONNX_PATH) / (1024**2):.2f} MB")

DATASET_PATH = Path('/content/drive/MyDrive/AutomaticHeartSoundClassification-main/data')
sys.path.append(str(DATASET_PATH))

features_file = DATASET_PATH / "mfcc_features.h5"
label_file = DATASET_PATH / "label_balanced.csv"

# Load labels để biết số sample
labels = pd.read_csv(label_file)
num_samples = len(labels)

# Load một phần features làm representative dataset (100-300 samples là đủ)
def representative_data_gen():
    with h5py.File(features_file, 'r') as hf:
        for i in range(300):  # Dùng 300 samples để calibrate
            idx = i % num_samples
            key = list(hf.keys())[idx]  # Hoặc hf['features'][idx] nếu là array
            data = hf[key][()]
            data = np.expand_dims(data, axis=0)  # Add batch dim
            data = data.astype(np.float32)
            yield [data]

print("✅ Đã chuẩn bị representative dataset từ mfcc_features.h5")

"""# CONVERT ONNX -> TFLITE"""

import onnx
m = onnx.load(ONNX_PATH)
print("IR version:", m.ir_version)

'''
import onnx

from onnxsim import simplify

model = onnx.load(ONNX_PATH)
model_simp, check = simplify(model)

onnx.save(model_simp, f"{MODEL_NAME.lower()}_{TIMESTAMP}_final.onnx")
'''

import onnxruntime as ort
try:
    # Thử nạp model bằng ONNX Runtime
    session = ort.InferenceSession(str(ONNX_PATH))
    print("✅ Model ONNX hợp lệ và sẵn sàng chuyển đổi TFLite.")
except Exception as e:
    print(f"❌ Model vẫn lỗi cấu trúc: {e}")

import h5py
import numpy as np
import librosa
from pathlib import Path

PROJECT_PATH = Path('/content/drive/MyDrive/AutomaticHeartSoundClassification-main')
DATASET_PATH = PROJECT_PATH / "data"
features_file = DATASET_PATH / "mfcc_features.h5"

DURATION = 5
HOP_LENGTH_MS = 15
FIXED_LENGTH = int(DURATION * 1000 / HOP_LENGTH_MS)  # 333
DELTA = False
NORM = True

def standard_normal_variate(data):
    mean = np.mean(data)
    std = np.std(data) + 1e-8
    return (data - mean) / std

calib_data_list = []

with h5py.File(features_file, 'r') as hf:
    all_keys = list(hf.keys())
    num_samples = len(all_keys)
    print(f"Total samples: {num_samples}")

    for i in range(300):
        key = all_keys[i % num_samples]
        feature = hf[key][()]
        '''
        if NORM:
            feature = standard_normal_variate(feature)

        if feature.ndim == 2:
            feature = feature[np.newaxis, :, :]

        if DELTA:
            orig = feature[0]
            delta1 = librosa.feature.delta(orig)
            delta2 = librosa.feature.delta(delta1)
            feature = np.stack([orig, delta1, delta2], axis=0)

        channels, mel_bins, num_frames = feature.shape

        if num_frames >= FIXED_LENGTH:
            start = num_frames // 2 - FIXED_LENGTH // 2
            feature = feature[:, :, start:start + FIXED_LENGTH]
        else:
            pad_width = FIXED_LENGTH - num_frames
            feature = np.pad(feature, ((0,0), (0,0), (0, pad_width)), mode='wrap')

        if channels > 1:
            feature = feature.reshape(channels * mel_bins, FIXED_LENGTH)  # (384, 333)

        feature = feature.astype(np.float32)
        feature = np.expand_dims(feature, axis=0)  # (1, 384, 333)
        calib_data_list.append(feature)
        '''
        if NORM:
            feature = standard_normal_variate(feature)

        # Crop / pad
        if feature.shape[1] >= FIXED_LENGTH:
            start = feature.shape[1] // 2 - FIXED_LENGTH // 2
            feature = feature[:, start:start + FIXED_LENGTH]
        else:
            pad_width = FIXED_LENGTH - feature.shape[1]
            feature = np.pad(feature, ((0,0),(0,pad_width)), mode='wrap')

        # Shape: (1, 39, 333)
        feature = feature.astype(np.float32)[None, :, :]
        calib_data_list.append(feature)

        if (i + 1) % 50 == 0:
            print(f"Prepared {i + 1}/300 calibration samples")

# Ghép thành array (300, 1, 39, 333) rồi lưu .npy
calibration_data = np.concatenate(calib_data_list, axis=0)
np.save("calib_data.npy", calibration_data)
print("✅ Đã lưu file calib_data.npy (shape:", calibration_data.shape, ")")

import onnx
from pathlib import Path

PROJECT_PATH = Path('/content/drive/MyDrive/AutomaticHeartSoundClassification-main')
TFLITE_DIR = PROJECT_PATH / "TFLITE"

model_prefix = f"{MODEL_NAME.lower()}_{TIMESTAMP}"

onnx_files = (
    list(TFLITE_DIR.glob(f"{model_prefix}_final.onnx")) +
    list(TFLITE_DIR.glob(f"{model_prefix}.onnx"))
)

if not onnx_files:
    raise FileNotFoundError(f"Không tìm thấy ONNX cho {model_prefix}")

# Lấy file mới nhất (phòng trường hợp export nhiều lần)
onnx_path = max(onnx_files, key=lambda p: p.stat().st_mtime)

print(f"Đang dùng ONNX: {onnx_path.name}")

model = onnx.load(str(onnx_path))
input_name = model.graph.input[0].name
print(f"Tên input OP trong ONNX: '{input_name}'")

from pathlib import Path
import onnx2tf

# =========================
# 1. PATH CONFIGURATION
# =========================

OUTPUT_TFLITE_DIR = TFLITE_DIR / f"{MODEL_NAME.lower()}_tflite_int8_{TIMESTAMP}"
output_folder_path=str(OUTPUT_TFLITE_DIR),

onnx_files = (
    list(TFLITE_DIR.glob(f"{MODEL_NAME.lower()}_{TIMESTAMP}_final.onnx")) +
    list(TFLITE_DIR.glob(f"{MODEL_NAME.lower()}_{TIMESTAMP}.onnx"))
)

if not onnx_files:
    raise FileNotFoundError(f"Không tìm thấy file ONNX trong {TFLITE_DIR}")

onnx_path = sorted(
    onnx_files,
    key=lambda p: p.stat().st_mtime,
    reverse=True
)[0]

print(f"Đang dùng ONNX: {onnx_path.name}")

json_path = OUTPUT_TFLITE_DIR / f"{onnx_path.stem}_auto.json"

print(f"Kiểm tra file cấu hình: {json_path}")

# 2. ONNX → TFLITE INT8
# CNN and VGG
onnx2tf.convert(
    input_onnx_file_path=str(onnx_path),
    output_folder_path=(OUTPUT_TFLITE_DIR),

    param_replacement_file=str(json_path) if json_path.exists() else None,

    # --- TFLite settings ---
    copy_onnx_input_output_names_to_tflite=True,
    output_integer_quantized_tflite=True,
    quant_type="per-tensor",   # có thể đổi sang "per-channel"

    # --- FIX SHAPE (RẤT QUAN TRỌNG) ---
    batch_size=1,
    overwrite_input_shape=[
        "input:1,39,333" # 1 Batch, 39 MFCC Coeffs (including Delta), 333 Time frames
    ],

    # --- INT8 CALIBRATION DATA ---
    custom_input_op_name_np_data_path=[
        [
            "input",            # tên input trong ONNX
            "calib_data.npy",   # (300, 39, 333)
            0.0,                # mean
            1.0                 # std
        ]
    ],

    non_verbose=False
)

print("Chuyển đổi thành công sang TFLite INT8!")
print(
    f"Output nằm trong thư mục: "
    f"{MODEL_NAME.lower()}_tflite_int8_{TIMESTAMP}/"
)

"""# Test Model"""

OUTPUT_TFLITE_DIR = TFLITE_DIR / f"{MODEL_NAME.lower()}_tflite_int8_{TIMESTAMP}"

from pathlib import Path

output_dir = Path(OUTPUT_TFLITE_DIR)
print("Các file/thư mục trong output:")
for item in output_dir.iterdir():
    print(item.name)

import tensorflow as tf
from pathlib import Path


print(f"Đang kiểm tra thư mục: {OUTPUT_TFLITE_DIR}\n")

# Kiểm tra xem thư mục có tồn tại không
if not OUTPUT_TFLITE_DIR.exists():
    raise FileNotFoundError(f"Thư mục không tồn tại: {OUTPUT_TFLITE_DIR}\n"
                            "Hãy kiểm tra lại tên thư mục hoặc chạy lại phần chuyển đổi ONNX → TFLite.")

# Liệt kê tất cả file .tflite trong thư mục
tflite_files = list(OUTPUT_TFLITE_DIR.glob("*.tflite"))

if not tflite_files:
    raise FileNotFoundError(f"Không tìm thấy file .tflite nào trong {OUTPUT_TFLITE_DIR}")

# In danh sách file kèm kích thước
print("=== DANH SÁCH FILE TFLITE & KÍCH THƯỚC ===")
def format_size(size_bytes):
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size_bytes < 1024:
            return f"{size_bytes:.2f} {unit}"
        size_bytes /= 1024
    return f"{size_bytes:.2f} TB"

for file_path in sorted(tflite_files):
    size = file_path.stat().st_size
    print(f"{file_path.name:<55} {format_size(size)}")

print()  # dòng trống

# Chọn file INT8 ưu tiên (có chứa "integer", "int8", "quant")
int8_file = next(
    (f for f in tflite_files if any(keyword in f.name.lower() for keyword in ["integer", "int8", "quant"])),
    tflite_files[0]  # nếu không có thì dùng file đầu tiên
)

print(f"Đang test với: {int8_file.name} ({format_size(int8_file.stat().st_size)})\n")

# Load và test model
interpreter = tf.lite.Interpreter(model_path=str(int8_file))
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print("=== THÔNG TIN INPUT ===")
for i, detail in enumerate(input_details):
    print(f"Input {i}:")
    print(f"  Name: {detail['name']}")
    print(f"  Shape: {detail['shape']}")
    print(f"  Dtype: {detail['dtype']}")
    print(f"  Quantization: {detail['quantization']}")

print("\n=== THÔNG TIN OUTPUT ===")
for detail in output_details:
    print(f"Output shape: {detail['shape']}")

import h5py
import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import librosa
from pathlib import Path

PROJECT_PATH = Path('/content/drive/MyDrive/AutomaticHeartSoundClassification-main')
DATASET_PATH = PROJECT_PATH / "data"

features_file = DATASET_PATH / "mfcc_features.h5"
label_file = DATASET_PATH / "label_balanced.csv"

# ================== LOGMEL DATASET ==================
EPS = 1e-8

def standard_normal_variate(data):
    mean = np.mean(data)
    std = np.std(data) + EPS
    return (data - mean) / std

class MFCCDataset(Dataset):
    def __init__(
        self,
        features_h5_path,
        label_csv_path,
        keys=None,
        norm=True,
        duration=5,
        hop_length=15,
        training=False
    ):
        self.features_h5 = h5py.File(features_h5_path, 'r')
        self.labels_df = pd.read_csv(label_csv_path)

        self.keys = list(self.features_h5.keys()) if keys is None else keys
        self.key_to_label = dict(
            zip(
                self.labels_df.iloc[:, 0].astype(str),
                self.labels_df.iloc[:, 1]
            )
        )

        self.norm = norm
        self.training = training
        self.fixed_length = int(duration * 1000 / hop_length)  # 333

    def __len__(self):
        return len(self.keys)

    def __getitem__(self, idx):
        key = self.keys[idx]

        # MFCC gốc: (13, T)
        mfcc = self.features_h5[key][()].astype(np.float32)

        if self.norm:
            mfcc = standard_normal_variate(mfcc)

        n_mfcc, T = mfcc.shape

        # crop / pad time axis
        if T >= self.fixed_length:
            start = (T - self.fixed_length) // 2
            mfcc = mfcc[:, start:start + self.fixed_length]
        else:
            pad = self.fixed_length - T
            mfcc = np.pad(mfcc, ((0, 0), (0, pad)), mode="constant")

        # FINAL SHAPE: (13, 333)
        feature_tensor = torch.from_numpy(mfcc)
        label = torch.tensor(self.key_to_label.get(key, 0), dtype=torch.long)

        return feature_tensor, label

    def close(self):
        self.features_h5.close()

import h5py
from torch.utils.data import DataLoader

# ============================================================
# LOAD ALL KEYS FROM MFCC HDF5
# ============================================================
with h5py.File(features_file, 'r') as hf:
    all_keys = list(hf.keys())

print(f"Tổng số mẫu: {len(all_keys)}")

# ============================================================
# CREATE FULL DATASET FOR FINAL EVALUATION (MFCC)
# ============================================================
full_dataset = MFCCDataset(
    features_h5_path=features_file,
    label_csv_path=label_file,
    keys=all_keys,
    #use_delta=True,     # MFCC + Δ + Δ² → 39 coefficients
    norm=True,
    duration=5,
    hop_length=15,
    training=False      # không random crop (center crop)
)

# ============================================================
# DATALOADER
# ============================================================
full_loader = DataLoader(
    full_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("✅ Đã tạo DataLoader MFCC thành công!")

def test_tflite_accuracy(tflite_path, data_loader):
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    _, T, F = input_details[0]['shape']  # (1, time, freq)

    print(f"Testing model: {tflite_path.name}")
    print(f"Expected input shape: (1, {T}, {F})")

    correct, total = 0, 0

    for features, labels in data_loader:
        for i in range(features.shape[0]):
            x = features[i].numpy()  # (freq, time) hoặc (time, freq)

            # Chuẩn hóa về (time, freq)
            if x.shape == (F, T):
                x = x.T
            elif x.shape != (T, F):
                raise ValueError(
                    f"Feature shape mismatch: got {x.shape}, expected {(T, F)}"
                )

            #x = np.expand_dims(x, axis=0).astype(np.float32)
            #interpreter.set_tensor(input_details[0]['index'], x)
            scale, zero_point = input_details[0]['quantization']
            if input_details[0]['dtype'] == np.int8:
                x_input = (x / scale + zero_point).astype(np.int8)
            else:
                x_input = x.astype(np.float32)

            x_input = np.expand_dims(x_input, axis=0)

            interpreter.set_tensor(input_details[0]['index'], x_input)

            interpreter.invoke()
            output = interpreter.get_tensor(output_details[0]['index'])

            pred = np.argmax(output, axis=1)[0]
            if pred == labels[i].item():
                correct += 1
            total += 1

    acc = correct / total
    print(f"=> Accuracy: {acc*100:.2f}% ({correct}/{total})")
    return acc

from pathlib import Path

# Tìm file INT8
tflite_files = list(OUTPUT_TFLITE_DIR.glob("*integer*.tflite")) + list(OUTPUT_TFLITE_DIR.glob("*quant*.tflite"))
if not tflite_files:
    raise FileNotFoundError("Không tìm thấy file TFLite INT8!")

int8_tflite_path = tflite_files[0]
print(f"Đang test với: {int8_tflite_path.name}")

# Chạy test
test_tflite_accuracy(int8_tflite_path, full_loader)

# Đóng dataset
full_dataset.close()

"""## Validation"""

PROJECT_PATH = Path('/content/drive/MyDrive/AutomaticHeartSoundClassification-main')
DATASET_PATH = PROJECT_PATH / "data"

features_file = DATASET_PATH / "mfcc_features_validation.h5"
label_file = DATASET_PATH / "label_validation.csv"

import h5py
from torch.utils.data import DataLoader

# ============================================================
# LOAD ALL KEYS FROM MFCC HDF5
# ============================================================
with h5py.File(features_file, 'r') as hf:
    all_keys = list(hf.keys())

print(f"Tổng số mẫu: {len(all_keys)}")

# ============================================================
# CREATE FULL DATASET FOR FINAL EVALUATION (MFCC)
# ============================================================
full_dataset = MFCCDataset(
    features_h5_path=features_file,
    label_csv_path=label_file,
    keys=all_keys,
    #use_delta=False,     # MFCC + Δ + Δ² → 39 coefficients
    norm=True,
    duration=5,
    hop_length=15,
    training=False      # không random crop (center crop)
)

# ============================================================
# DATALOADER
# ============================================================
full_loader = DataLoader(
    full_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("✅ Đã tạo DataLoader MFCC thành công!")

from pathlib import Path

# Tìm file INT8
tflite_files = list(OUTPUT_TFLITE_DIR.glob("*integer*.tflite")) + list(OUTPUT_TFLITE_DIR.glob("*quant*.tflite"))
if not tflite_files:
    raise FileNotFoundError("Không tìm thấy file TFLite INT8!")

int8_tflite_path = tflite_files[0]
print(f"Đang test với: {int8_tflite_path.name}")

# Chạy test
test_tflite_accuracy(int8_tflite_path, full_loader)

# Đóng dataset
full_dataset.close()